'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ITmanagementEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ITmanagementEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tblAccessLists() As DbSet(Of tblAccessList)
    Public Overridable Property tblAccessListDetails() As DbSet(Of tblAccessListDetail)
    Public Overridable Property tblMasterCodes() As DbSet(Of tblMasterCode)
    Public Overridable Property tblDepartments() As DbSet(Of tblDepartment)

End Class
