'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblDepartment
    Public Property Branch As String
    Public Property Party As String
    Public Property Department As String
    Public Property Manager As String
    Public Property A_Manager As String
    Public Property Status As Nullable(Of Integer)
    Public Property Userby As String
    Public Property Lastupdate As Nullable(Of Date)

End Class
